version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: enpal-coding-challenge-app
    ports:
      - "3000:3000"  # Map host port 3000 to container port 3000
    environment:
      - DB_HOST=db
      - DB_DSN=postgres://postgress:mypassword123!@db:5432/coding-challenge?sslmode=disable
      - DB_PORT=5432
      - DB_USER=postgress
      - DB_PASSWORD=mypassword123!
      - DB_NAME=coding-challenge
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: enpal-coding-challenge-db
    environment:
      POSTGRES_DB: coding-challenge
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: mypassword123!
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
